stages:
  - build
  - test

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
container_scanning:
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - "update clang11"
    - "update clang12"
    - "update clang13"
    - "update clang14"
    - "update clang15"

.test-base:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install click
  script:
    - apk add python3 py3-pip
    - python3 ./tool.py test $IMAGE_DIR
  except:
    - main

.update-base:
  extends: .test-base
  script:
    - python3 ./tool.py update $IMAGE_DIR
  except: []
  only:
    - main

test clang11:
  extends: .test-base
  variables:
    IMAGE_DIR: clang11

update clang11:
  extends: .update-base
  variables:
    IMAGE_DIR: clang11

test clang12:
  extends: .test-base
  variables:
    IMAGE_DIR: clang12

update clang12:
  extends: .update-base
  variables:
    IMAGE_DIR: clang12

test clang13:
  extends: .test-base
  variables:
    IMAGE_DIR: clang13

update clang13:
  extends: .update-base
  variables:
    IMAGE_DIR: clang13

test clang14:
  extends: .test-base
  variables:
    IMAGE_DIR: clang14

update clang14:
  extends: .update-base
  variables:
    IMAGE_DIR: clang14

test clang15:
  extends: .test-base
  variables:
    IMAGE_DIR: clang15

update clang15:
  extends: .update-base
  variables:
    IMAGE_DIR: clang15
