stages:
  - build
  - publish

variables:
  HUB_REPO_NAME: musicscience37/sphinx-doxygen

.build-base:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$IMAGE_NAME" "$IMAGE_DIR"
    - sh run_test.sh "$IMAGE_DIR"
    - docker push "$IMAGE_NAME"
  artifacts:
    paths:
      - test/build
    expire_in: "30 days"

.build-hub-base:
  extends: .build-base
  after_script:
    - docker login -u "$HUB_USER_NAME" -p "$HUB_ACCESS_TOKEN"
    - docker tag "$IMAGE_NAME" "$HUB_IMAGE_NAME"
    - docker push "$HUB_IMAGE_NAME"

build clang12:
  extends: .build-base
  variables:
    IMAGE_DIR: clang12
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_DIR-$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build tag clang12:
  extends: .build-hub-base
  variables:
    IMAGE_DIR: clang12
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_DIR-$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$IMAGE_DIR-$CI_COMMIT_TAG"
  only:
    - tags

build clang13:
  extends: .build-base
  variables:
    IMAGE_DIR: clang13
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_DIR-$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build tag clang13:
  extends: .build-hub-base
  variables:
    IMAGE_DIR: clang13
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_DIR-$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$IMAGE_DIR-$CI_COMMIT_TAG"
  only:
    - tags

build clang14:
  extends: .build-base
  variables:
    IMAGE_DIR: clang14
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_DIR-$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build tag clang14:
  extends: .build-hub-base
  variables:
    IMAGE_DIR: clang14
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_DIR-$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$IMAGE_DIR-$CI_COMMIT_TAG"
  only:
    - tags

build tag:
  extends: .build-hub-base
  variables:
    IMAGE_DIR: clang12
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$CI_COMMIT_TAG"
  only:
    - tags

build master:
  extends: .build-hub-base
  variables:
    IMAGE_DIR: clang12
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:latest"
  only:
    - master

pages:
  only:
    - master
  stage: publish
  image: ubuntu
  script:
    - cp -r test/build/sphinx/html public
  artifacts:
    paths:
      - public
    expire_in: "6 mos"
