stages:
  - build
  - test

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
container_scanning:
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - IMAGE_TAG:
          - clang12
          - clang13
          - clang14
          - clang15
          - clang16
          - clang17
          - clang18
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install click
  script:
    - python3 ./tool.py test $IMAGE_TAG

update:
  extends: test
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - python3 ./tool.py update $IMAGE_TAG
